structure(list(url = "https://statcubeapi.statistik.at/statistik.at/ext/statcube/rest/v1/table/saved/str:table:invalid_uri", 
    status_code = 400L, headers = structure(list(`x-ratelimit-schema` = "10000", 
        `x-ratelimit-remaining-schema` = "9997", `x-ratelimit-reset-schema` = "1677755851269", 
        `x-ratelimit-table` = "100", `x-ratelimit-remaining-table` = "95", 
        `x-ratelimit-reset-table` = "1677755851269", `content-security-policy` = "default-src 'self' *.statistik.at *.local *.statcube.at 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.statistik.at *.statcube.at *.local", 
        `content-encoding` = "gzip", `content-type` = "application/json;charset=UTF-8", 
        date = "Thu, 02 Mar 2023 10:41:36 GMT", `x-cnection` = "close", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(`x-ratelimit-schema` = "10000", 
            `x-ratelimit-remaining-schema` = "9997", `x-ratelimit-reset-schema` = "1677755851269", 
            `x-ratelimit-table` = "100", `x-ratelimit-remaining-table` = "95", 
            `x-ratelimit-reset-table` = "1677755851269", `content-security-policy` = "default-src 'self' *.statistik.at *.local *.statcube.at 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.statistik.at *.statcube.at *.local", 
            `content-encoding` = "gzip", `content-type` = "application/json;charset=UTF-8", 
            date = "Thu, 02 Mar 2023 10:41:36 GMT", `x-cnection` = "close", 
            `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_statcubeapi.statistik.at", 
    "#HttpOnly_statcubeapi.statistik.at", "statcubeapi.statistik.at"
    ), flag = c(FALSE, FALSE, FALSE), path = c("/", "/statistik.at/ext/statcube/rest/v1/", 
    "/"), secure = c(FALSE, TRUE, FALSE), expiration = structure(c(Inf, 
    Inf, Inf), class = c("POSIXct", "POSIXt")), name = c("statistik_cookie", 
    "f5avraaaaaaaaaaaaaaaa_session_", "TS017b3bc9"), value = c("REDACTED", 
    "REDACTED", "REDACTED")), row.names = c(NA, -3L), class = "data.frame"), 
    content = charToRaw("{\"message\":\"The requested TXD 'str:table:invalid_uri' could not be found for the current user.\",\"errorType\":\"TXD_NOT_FOUND\",\"component\":\"str:table:invalid_uri\"}"), 
    date = structure(1677753696, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.8e-05, 
    connect = 2.9e-05, pretransfer = 0.000104, starttransfer = 1.48272, 
    total = 1.482824)), class = "response")
