---
title: "Setup the API Key"
description: >
  Set up authentication to the STATcube REST API by setting your API key
  for the session or persistently.
---

Instructions for the first-time use of the STATcube REST API.

## Adding an API key

In order to use the REST API of STATcube it is necessary to provide
an API key. If your STATcube account is configured to use a key,
the following address can be used to view your key

```
http://sdbext:8081/statistik.at/ext/statcube/jsf/preferences/editPreferences.xhtml
```

To make the key available to `{STATcubeR}`, use the function
`sc_key_set()`. Replace `"XXXX"` with your key.

```r
sc_key_set("XXXX")
#> The provided key will be available for this R session. Add
#>
#>   STATCUBE_KEY=XXXX
#>
#> to your .Renviron to set the key persistently
```

As suggested by the code output, the key can be set persistently by modifying
`.Renviron`. This can be done easily with `usethis::edit_r_environ()`.

## How do I get an API key?

Currently, the api is only available inside the firewall of statistics austria.
Therefore, api keys can only be requested by our employees. Api access for
external users with a statcube subscription is planned in the near future.
Please get into contact with the package maintainers of `{STATcubeR}` for details.

## Next Steps

See the [JSON requests article](JSON-requests.html) to see how tables can be
defined in the STATcube GUI and imported into R.
Alternatively, import a saved table by following the
[saved tables article](Saved-Tables.html)
