---
title: "Setup"
---

Instructions for the first-time use of `STATcubeR`.

## Installation

The package can be installed directly from github using the
`remotes` package.

``` r
remotes::install_github("statistikat/STATcubeR")
```

## Adding an API token

In order to use the REST API of STATcube it is necessary to provide
an API token. If your STATcube account is configured to use a token,
the following address can be used to view your token.

```
http://sdbext:8081/statistik.at/ext/statcube/jsf/preferences/editPreferences.xhtml
```

To make the token available to `STATcubeR`, use the function
`statcube_token_set()`. Replace `"XXXX"` with your token.

```r
sc_token_set("XXXX")
#> The provided token will be available for this R session. Add
#>
#>   STATCUBE_TOKEN=XXXX
#>
#> to your .Renviron to set the token persistently
```

## How do I get an API token?

Currently, the api is only available inside the firewall of statistics austria.
Therefore, api tokens can only be requested by our employees. Api access for
external users with a statcube subscription is planned for spring 2021. Please
get into contact with the package maintainers of `STATcubeR` for details.
