structure(list(url = "https://statcubeapi.statistik.at/statistik.at/ext/statcube/rest/v1/schema/invalid_uri", 
    status_code = 400L, headers = structure(list(`x-ratelimit-schema` = "10000", 
        `x-ratelimit-remaining-schema` = "9997", `x-ratelimit-reset-schema` = "1677755851269", 
        `x-ratelimit-table` = "100", `x-ratelimit-remaining-table` = "95", 
        `x-ratelimit-reset-table` = "1677755851269", `content-security-policy` = "default-src 'self' *.statistik.at *.local *.statcube.at 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.statistik.at *.statcube.at *.local", 
        `content-encoding` = "gzip", `content-type` = "application/json;charset=UTF-8", 
        date = "Thu, 02 Mar 2023 10:47:30 GMT", `x-cnection` = "close", 
        `set-cookie` = "REDACTED", `set-cookie` = "REDACTED", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(`x-ratelimit-schema` = "10000", 
            `x-ratelimit-remaining-schema` = "9997", `x-ratelimit-reset-schema` = "1677755851269", 
            `x-ratelimit-table` = "100", `x-ratelimit-remaining-table` = "95", 
            `x-ratelimit-reset-table` = "1677755851269", `content-security-policy` = "default-src 'self' *.statistik.at *.local *.statcube.at 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.statistik.at *.statcube.at *.local", 
            `content-encoding` = "gzip", `content-type` = "application/json;charset=UTF-8", 
            date = "Thu, 02 Mar 2023 10:47:30 GMT", `x-cnection` = "close", 
            `set-cookie` = "REDACTED", `set-cookie` = "REDACTED", 
            `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_statcubeapi.statistik.at", 
    "#HttpOnly_statcubeapi.statistik.at", "statcubeapi.statistik.at", 
    "#HttpOnly_statcubeapi.statistik.at"), flag = c(FALSE, FALSE, 
    FALSE, FALSE), path = c("/", "/statistik.at/ext/statcube/rest/v1/", 
    "/", "/statistik.at/ext/statcube/rest/v1/schema/"), secure = c(FALSE, 
    TRUE, FALSE, TRUE), expiration = structure(c(Inf, Inf, Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("statistik_cookie", 
    "f5avraaaaaaaaaaaaaaaa_session_", "TS017b3bc9", "f5avraaaaaaaaaaaaaaaa_session_"
    ), value = c("REDACTED", "REDACTED", "REDACTED", "REDACTED"
    )), row.names = c(NA, -4L), class = "data.frame"), content = charToRaw("{\"message\":\"Could not find the requested component: invalid_uri.\",\"errorType\":\"SCHEMA_COMPONENT_NOT_FOUND\",\"component\":\"invalid_uri\"}"), 
    date = structure(1677754050, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.002627, 
    connect = 0.009886, pretransfer = 0.047192, starttransfer = 1.42687, 
    total = 1.427035)), class = "response")
