structure(list(url = "https://statcubeapi.statistik.at/statistik.at/ext/statcube/rest/v1/table", 
    status_code = 400L, headers = structure(list(`x-ratelimit-schema` = "10000", 
        `x-ratelimit-remaining-schema` = "9997", `x-ratelimit-reset-schema` = "1677755851269", 
        `x-ratelimit-table` = "100", `x-ratelimit-remaining-table` = "95", 
        `x-ratelimit-reset-table` = "1677755851269", `content-security-policy` = "default-src 'self' *.statistik.at *.local *.statcube.at 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.statistik.at *.statcube.at *.local", 
        `content-encoding` = "gzip", `content-type` = "application/json;charset=UTF-8", 
        date = "Thu, 02 Mar 2023 10:36:48 GMT", `x-cnection` = "close", 
        `set-cookie` = "REDACTED", `set-cookie` = "REDACTED", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(`x-ratelimit-schema` = "10000", 
            `x-ratelimit-remaining-schema` = "9997", `x-ratelimit-reset-schema` = "1677755851269", 
            `x-ratelimit-table` = "100", `x-ratelimit-remaining-table` = "95", 
            `x-ratelimit-reset-table` = "1677755851269", `content-security-policy` = "default-src 'self' *.statistik.at *.local *.statcube.at 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.statistik.at *.statcube.at *.local", 
            `content-encoding` = "gzip", `content-type` = "application/json;charset=UTF-8", 
            date = "Thu, 02 Mar 2023 10:36:48 GMT", `x-cnection` = "close", 
            `set-cookie` = "REDACTED", `set-cookie` = "REDACTED", 
            `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_statcubeapi.statistik.at", 
    "#HttpOnly_statcubeapi.statistik.at", "statcubeapi.statistik.at"
    ), flag = c(FALSE, FALSE, FALSE), path = c("/", "/statistik.at/ext/statcube/rest/v1/", 
    "/"), secure = c(FALSE, TRUE, FALSE), expiration = structure(c(Inf, 
    Inf, Inf), class = c("POSIXct", "POSIXt")), name = c("statistik_cookie", 
    "f5avraaaaaaaaaaaaaaaa_session_", "TS017b3bc9"), value = c("REDACTED", 
    "REDACTED", "REDACTED")), row.names = c(NA, -3L), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Your request exceeds the configured cell limit of 1,000,000. It contains at least 21,976,902 cells.\",\"errorType\":\"CELL_COUNT\",\"value\":21976902,\"limit\":1000000}"), 
    date = structure(1677753408, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3e-05, 
    connect = 0.006897, pretransfer = 0.047706, starttransfer = 1.847266, 
    total = 1.850284)), class = "response")
